CanalTP\MethBundle\Entity\Block:
    type: entity
    table: null
    repositoryClass: CanalTP\MethBundle\Entity\BlockRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        typeId:
            type: string
            column: type_id
        domId:
            type: string
            length: '128'
            column: dom_id
        content:
            type: text
        title:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    manyToOne:
        line:
            targetEntity: Line
            inversedBy: blocks
            joinColumn:
                name: line_id
                referencedColumnName: id
        stopPoint:
            targetEntity: StopPoint
            inversedBy: blocks
            joinColumn:
                name: stop_point_id
                referencedColumnName: id
