CanalTP\MttBundle\Entity\DistributionList:
    type: entity
    table: mtt.distribution_list
    repositoryClass: CanalTP\MttBundle\Entity\DistributionListRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
        externalRouteId:
            type: string
            length: 255
            column: external_route_id
        includedStops:
            type: array
            column: included_stops
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    uniqueConstraints:
        network_external_route_idx:
            columns: [ network_id, external_route_id ]
    manyToOne:
        network:
            targetEntity: Network
            inversedBy: mtt.ditribution_lists
            joinColumn:
                name: network_id
                referencedColumnName: id
