CanalTP\MethBundle\Entity\Line:
    type: entity
    table: line
    repositoryClass: CanalTP\MethBundle\Entity\LineRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        externalCoverageId:
            type: string
            length: 255
            column: external_coverage_id
        externalNetworkId:
            type: string
            length: 255
            column: external_network_id
        externalId:
            type: string
            length: 255
            column: external_id
        layout:
            type: string
            column: layout
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
