CanalTP\MttBundle\Entity\Line:
    type: entity
    table: mtt.line
    repositoryClass: CanalTP\MttBundle\Entity\LineRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        externalId:
            type: string
            length: 255
            column: external_id
        layout:
            type: string
            column: layout
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
