CanalTP\MethBundle\Entity\Network:
    type: entity
    table: network
    repositoryClass: CanalTP\MethBundle\Entity\NetworkRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        externalId:
            type: string
            length: 255
            column: external_id
        externalCoverageId:
            type: string
            length: 255
            column: external_coverage_id
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToMany:
        users:
            targetEntity: CanalTP\CoreBoBundle\Entity\User
            joinTable:
                name: users_networks
                joinColumns:
                    network_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
