CanalTP\MttBundle\Entity\Timetable:
    type: entity
    table: mtt.timetable
    repositoryClass: CanalTP\MttBundle\Entity\TimetableRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
        externalRouteId:
            type: string
            length: 255
            column: external_route_id
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        blocks:
            targetEntity: Block
            mappedBy: timetable
        ditributionLists:
            targetEntity: DistributionList
            mappedBy: timetable
        stopPoints:
            targetEntity: StopPoint
            mappedBy: timetable
    manyToOne:
        line_config:
            targetEntity: LineConfig
            joinColumn:
                name: line_config_id
                referencedColumnName: id