CanalTP\MttBundle\Entity\Timetable:
    type: entity
    table: mtt.timetable
    repositoryClass: CanalTP\MttBundle\Entity\TimetableRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        externalRouteId:
            type: string
            length: 255
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        blocks:
            targetEntity: Block
            mappedBy: timetable
        ditributionLists:
            targetEntity: DistributionList
            mappedBy: timetable
