parameters:
    blocks:
        text:
            label: Text block type
            icon: edit
        img:
            label: Image block type
            icon: picture
        timegrid:
            label: Timegrid block type
            icon: calendar