parameters:
    layouts:
        layout_1:
            label: Layout 1 de type paysage (exemple Dijon)
            twig: layout_1.html.twig
            preview: /bundles/canaltpmtt/img/layout_1.png
            orientation: landscape
        layout_2:
            label: Layout 2 de type paysage (exemple Brest)
            twig: layout_2.html.twig
            preview: /bundles/canaltpmtt/img/layout_2.png
            orientation: landscape
