canal_tp_meth_homepage:
    pattern:  /
    defaults: { _controller: CanalTPMttBundle:Default:index }

canal_tp_meth_menu:
    pattern:  /navigation/{current_route}
    defaults: { _controller: CanalTPMttBundle:Default:navigation, current_route: null }

#StopPoint
canal_tp_meth_stop_point_list:
    pattern: /coverage/{coverage_id}/network/{network_id}/line/{line_id}/route/{externalRouteId}/list
    defaults: { _controller: CanalTPMttBundle:StopPoint:list }

#Line
canal_tp_meth_line_choose_layout:
    pattern: /coverage/{coverage_id}/network/{network_id}/line/{line_id}/choose_layout/route/{externalRouteId}
    defaults: { _controller: CanalTPMttBundle:Line:chooseLayout }

#Timetable
canal_tp_meth_timetable_edit:
    pattern: /timetable/edit/coverage/{externalCoverageId}/route/{externalRouteId}/stopPoint/{externalStopPointId}
    defaults: { _controller: CanalTPMttBundle:Timetable:edit, externalStopPointId: null }
    requirements:
        stopPoint: -?[a-zA-Z0-9_\-:]*

canal_tp_meth_timetable_view:
    pattern: /timetable/view/coverage/{externalCoverageId}/route/{externalRouteId}/stopPoint/{externalStopPointId}
    defaults: { _controller: CanalTPMttBundle:Timetable:view, externalStopPointId: null }
    requirements:
        stopPoint: -?[a-zA-Z0-9_\-:]*

canal_tp_meth_timetable_generate_pdf:
    pattern: /timetable/{timetableId}/coverage/{externalCoverageId}/stopPoint/{externalStopPointId}/generatePdf
    defaults: { _controller: CanalTPMttBundle:Timetable:generatePdf}

#Block
canal_tp_meth_block_edit:
    # stop point must be the last param so it can be empty
    pattern: /block/edit/coverage/{externalCoverageId}/dom_id/{dom_id}/timetable/{timetableId}/block_type/{block_type}/stop_point/{stop_point}
    defaults: { _controller: CanalTPMttBundle:Block:edit, block_type: null, stop_point: null }
    options:
        expose: true

canal_tp_meth_block_delete:
    # stop point must be the last param so it can be empty
    pattern: /block/delete/coverage/{externalCoverageId}/timetable/{timetableId}/blockId/{blockId}
    defaults: { _controller: CanalTPMttBundle:Block:delete }


#DistributionList
canal_tp_mtt_distribution_list:
    pattern: /coverage/{coverageId}/network/{networkId}/line/{lineId}/route/{routeId}/distribution/list
    defaults: { _controller: CanalTPMttBundle:Distribution:list}

canal_tp_meth_distribution_generate:
    pattern: /distribution/generate/timetable/{timetableId}/coverage/{externalCoverageId}
    defaults: { _controller: CanalTPMttBundle:Distribution:generate}
    options:
        expose: true

#Calendar
canal_tp_mtt_calendar_view:
    pattern: /calendars/view/coverage/{externalCoverageId}/route/{externalRouteId}/stopPoint/{externalStopPointId}
    defaults: { _controller: CanalTPMttBundle:Calendar:view}

#Frequency
canal_tp_mtt_frequency_edit:
    pattern: /frequency/edit/block/{blockId}/layout/{layoutId}/coverage/{externalCoverageId}/
    defaults: { _controller: CanalTPMttBundle:Frequency:edit}
