canal_tp_meth_homepage:
    pattern:  /
    defaults: { _controller: CanalTPMethBundle:Default:index }

canal_tp_meth_menu:
    pattern:  /navigation/{current_route}
    defaults: { _controller: CanalTPMethBundle:Default:navigation, current_route: null }

canal_tp_meth_stop_point_list:
    pattern: /coverage/{coverage_id}/network/{network_id}/line/{line_id}/route/{route_id}/list
    defaults: { _controller: CanalTPMethBundle:StopPoint:list }
    
canal_tp_meth_line_choose_layout:
    pattern: /coverage/{coverage_id}/network/{network_id}/line/{line_id}/choose_layout/route/{route_id}
    defaults: { _controller: CanalTPMethBundle:Line:chooseLayout }

canal_tp_meth_line_edit_layout:
    pattern: /line/{line_id}/edit_layout
    defaults: { _controller: CanalTPMethBundle:Line:editLayout }
    
canal_tp_meth_block_get_form:
    pattern: /get_form/dom_id/{dom_id}/block_type/{block_type}
    defaults: { _controller: CanalTPMethBundle:Block:getForm, block_type: null }
    options:
        expose: true