canal_tp_mtt_homepage:
    pattern:  /{externalNetworkId}
    defaults: { _controller: CanalTPMttBundle:Default:index , externalNetworkId: null}

canal_tp_mtt_menu:
    pattern:  /navigation/network/{externalNetworkId}/season/{current_season}/route/{current_route}
    defaults: { _controller: CanalTPMttBundle:Default:navigation, current_route: null }
    requirements:
        network_id: -?[a-zA-Z0-9_\-:]*
#Season
canal_tp_mtt_season_list:
    pattern: /network/{network_id}/seasons/list
    defaults: { _controller: CanalTPMttBundle:Season:list }
    requirements:
        network_id: -?[a-zA-Z0-9_\-:]*

canal_tp_mtt_season_edit:
    pattern: /network/{network_id}/edit/{season_id}
    defaults: { _controller: CanalTPMttBundle:Season:edit, season_id: null }
    requirements:
        network_id: -?[a-zA-Z0-9_\-:]*

#StopPoint
canal_tp_mtt_stop_point_list:
    pattern: /network/{network_id}/line/{line_id}/route/{externalRouteId}/list/season/{seasonId}
    defaults: { _controller: CanalTPMttBundle:StopPoint:list, seasonId: null }
    requirements:
        seasonId: \d+

#Line
canal_tp_mtt_line_choose_layout:
    pattern: /network/{externalNetworkId}/season/{seasonId}/line/{line_id}/choose_layout/route/{externalRouteId}
    defaults: { _controller: CanalTPMttBundle:Line:chooseLayout }

#Timetable
canal_tp_mtt_timetable_edit:
    pattern: /timetable/edit/network/{externalNetworkId}/line/{externalLineId}/route/{externalRouteId}/season/{seasonId}/stopPoint/{externalStopPointId}
    defaults: { _controller: CanalTPMttBundle:Timetable:edit, externalStopPointId: null }
    requirements:
        stopPoint: -?[a-zA-Z0-9_\-:]*

canal_tp_mtt_timetable_view:
    pattern: /timetable/view/network/{externalNetworkId}/line/{externalLineId}/route/{externalRouteId}/season/{seasonId}/stopPoint/{externalStopPointId}
    defaults: { _controller: CanalTPMttBundle:Timetable:view, externalStopPointId: null }
    requirements:
        stopPoint: -?[a-zA-Z0-9_\-:]*

canal_tp_mtt_timetable_generate_pdf:
    pattern: /timetable/{timetableId}/network/{externalNetworkId}/stopPoint/{externalStopPointId}/generatePdf
    defaults: { _controller: CanalTPMttBundle:Timetable:generatePdf}

#Block
canal_tp_mtt_block_edit:
    # stop point must be the last param so it can be empty
    pattern: /block/edit/network/{externalNetworkId}/dom_id/{dom_id}/timetable/{timetableId}/block_type/{block_type}/stop_point/{stop_point}
    defaults: { _controller: CanalTPMttBundle:Block:edit, block_type: null, stop_point: null }
    options:
        expose: true

canal_tp_mtt_block_delete:
    # stop point must be the last param so it can be empty
    pattern: /block/delete/network/{externalNetworkId}/timetable/{timetableId}/blockId/{blockId}
    defaults: { _controller: CanalTPMttBundle:Block:delete }


#DistributionList
canal_tp_mtt_distribution_list:
    pattern: network/{externalNetworkId}/line/{lineId}/route/{routeId}/distribution/season/{currentSeasonId}/list/{reset}
    defaults: { _controller: CanalTPMttBundle:Distribution:list, reset: null}

canal_tp_mtt_distribution_generate:
    pattern: /distribution/generate/timetable/{timetableId}/network/{externalNetworkId}
    defaults: { _controller: CanalTPMttBundle:Distribution:generate}
    options:
        expose: true

canal_tp_mtt_distribution_list_save:
    pattern: network/{externalNetworkId}/line/{lineId}/route/{routeId}/season/{currentSeasonId}/distribution/list/save/
    defaults: { _controller: CanalTPMttBundle:Distribution:save}
    options:
        expose: true
#Calendar
canal_tp_mtt_calendar_view:
    pattern: /calendars/view/network/{externalNetworkId}/route/{externalRouteId}/stopPoint/{externalStopPointId}/season/{currentSeasonId}
    defaults: { _controller: CanalTPMttBundle:Calendar:view, currentSeasonId: null}

#Frequency
canal_tp_mtt_frequency_edit:
    pattern: /frequency/edit/block/{blockId}/layout/{layoutId}/network/{externalNetworkId}/
    defaults: { _controller: CanalTPMttBundle:Frequency:edit}

#Network
canal_tp_mtt_network:
    pattern: /coverage/{coverage_id}/network/{network_id}/seasons/list
    defaults: { _controller: CanalTPMttBundle:Network:index }
canal_tp_mtt_network_list:
    pattern: /network/list
    defaults: { _controller: CanalTPMttBundle:Network:list }
canal_tp_mtt_network_edit:
    pattern: /network/edit/{network_id}
    defaults: { _controller: CanalTPMttBundle:Network:edit, network_id: null}

#Layouts
canal_tp_mtt_layouts:
    pattern: /layouts/network/{externalNetworkId}
    defaults: { _controller: CanalTPMttBundle:Layout:index}
