canal_tp_meth_homepage:
    pattern:  /
    defaults: { _controller: CanalTPMethBundle:Default:index }

canal_tp_meth_menu:
    pattern:  /navigation/{current_route}
    defaults: { _controller: CanalTPMethBundle:Default:navigation, current_route: null }

canal_tp_meth_stop_point_list:
    pattern: /coverage/{coverage_id}/network/{network_id}/line/{line_id}/route/{routeExternalId}/list
    defaults: { _controller: CanalTPMethBundle:StopPoint:list }

canal_tp_meth_line_choose_layout:
    pattern: /coverage/{coverage_id}/network/{network_id}/line/{line_id}/choose_layout/route/{route_id}
    defaults: { _controller: CanalTPMethBundle:Line:chooseLayout }

canal_tp_meth_timetable_edit:
    pattern: /timetable/coverage/{externalCoverageId}/route/{routeExternalId}/stopPoint/{stopPoint}/edit
    defaults: { _controller: CanalTPMethBundle:Timetable:edit, stopPoint: null }
    requirements:
        stopPoint: -?[a-zA-Z0-9_\-:]*

canal_tp_meth_timetable_view:
    pattern: /timetable/line/{line_id}/stopPoint/{stopPoint}/view
    defaults: { _controller: CanalTPMethBundle:Timetable:view, stopPoint: null }
    requirements:
        stopPoint: -?[a-zA-Z0-9_\-:]*

canal_tp_meth_block_edit:
    pattern: /edit/line_id/{line_id}/dom_id/{dom_id}/block_type/{block_type}/stop_point/{stop_point}
    defaults: { _controller: CanalTPMethBundle:Block:edit, block_type: null, stop_point: null }
    options:
        expose: true

canal_tp_meth_timetable_generate_pdf:
    pattern: /timetable/line/{lineId}/stopPoint/{stopPointId}/generatePdf
    defaults: { _controller: CanalTPMethBundle:Timetable:generatePdf}
        
canal_tp_meth_distribution_list:
    pattern: /coverage/{coverageId}/network/{networkId}/line/{lineId}/route/{routeId}/distribution/list
    defaults: { _controller: CanalTPMethBundle:Distribution:list}
    
canal_tp_meth_distribution_generate:
    pattern: /line/{lineId}/route/{routeId}/distribution/generate
    defaults: { _controller: CanalTPMethBundle:Distribution:generate}
    options:
        expose: true