canal_tp_meth_homepage:
    pattern:  /
    defaults: { _controller: CanalTPMethBundle:Default:index }
canal_tp_meth_menu:
    pattern:  /navigation
    defaults: { _controller: CanalTPMethBundle:Default:navigation }
