canal_tp_meth_homepage:
    pattern:  /
    defaults: { _controller: CanalTPMethBundle:Default:index }

canal_tp_meth_menu:
    pattern:  /navigation/{current_route}
    defaults: { _controller: CanalTPMethBundle:Default:navigation, current_route: null }

canal_tp_meth_stop_point_list:
    pattern: /coverage/{coverage_id}/network/{network_id}/line/{line_id}/route/{route_id}/list
    defaults: { _controller: CanalTPMethBundle:StopPoint:list }

canal_tp_meth_line_choose_layout:
    pattern: /coverage/{coverage_id}/network/{network_id}/line/{line_id}/choose_layout/route/{route_id}
    defaults: { _controller: CanalTPMethBundle:Line:chooseLayout }

canal_tp_meth_line_edit_layout:
    pattern: /timetable/line/{line_id}/stop_point/{stop_point}/edit
    defaults: { _controller: CanalTPMethBundle:Timetable:edit, stop_point: null }
    requirements:
        stop_point: -?\d*

canal_tp_meth_block_edit:
    pattern: /edit/line_id/{line_id}/dom_id/{dom_id}/block_type/{block_type}
    defaults: { _controller: CanalTPMethBundle:Block:edit, block_type: null }
    options:
        expose: true
