parameters:
    media_manager.class: CanalTP\MediaManagerBundle\DataCollector\MediaDataCollector
    canal_tp_mtt.user.class: CanalTP\MttBundle\Services\UserManager
    canal_tp_mtt.navitia.class: CanalTP\MttBundle\Services\Navitia
    canal_tp_mtt.line_manager.class: CanalTP\MttBundle\Services\LineManager
    canal_tp_mtt.timetable_manager.class: CanalTP\MttBundle\Services\TimetableManager
    canal_tp_mtt.stop_point_manager.class: CanalTP\MttBundle\Services\StopPointManager
    canal_tp_mtt.calendar_manager.class: CanalTP\MttBundle\Services\CalendarManager
    canal_tp_mtt.form.factory.class: CanalTP\MttBundle\Services\BlockTypeFactory
    canal_tp_mtt.form.image_type_extension.class: CanalTP\MttBundle\Form\Extension\ImageTypeExtension
    canal_tp_mtt.pdf_generator.class: CanalTP\MttBundle\Services\PdfGenerator
    canal_tp_mtt.block_manager.class: CanalTP\MttBundle\Services\BlockManager
    canal_tp_mtt.frequency_manager.class: CanalTP\MttBundle\Services\FrequencyManager
    canal_tp_mtt.season.class: CanalTP\MttBundle\Services\SeasonManager
    canal_tp_mtt.network.class: CanalTP\MttBundle\Services\NetworkManager

services:
    #Profiler
    data_collector.navitia:
        class: CanalTP\MttBundle\DataCollector\NavitiaDataCollector
        tags:
            - { name: data_collector, template: "CanalTPMttBundle:Collector:navitia", id: "navitia"  }
    canal_tp_mtt.matcher.navitia_debug:
        class: CanalTP\MttBundle\Profiler\NavitiaDebugMatcher
        arguments: ["@security.context"]
    # FORMS
    form.type.layout:
        class: CanalTP\MttBundle\Form\Type\LayoutType
        arguments:
            - "%layouts%"
        tags:
            - { name: form.type, alias: layout }
    form.type.datepicker:
        class: CanalTP\MttBundle\Form\Type\DatepickerType
        tags:
            - { name: form.type, alias: datepicker }
    # Service of mediaManager
    canaltp_media_manager_mtt:
        class: %media_manager.class%
        arguments: [%canal_tp_media_manager.configurations.mtt%]
    canal_tp_mtt.user:
       class: %canal_tp_mtt.user.class%
       arguments: ['@doctrine.orm.entity_manager', '@security.context', '@translator']
    canal_tp_mtt.navitia:
       class: %canal_tp_mtt.navitia.class%
       arguments: ['@navitia_component', '@sam_navitia', '@translator']
    canal_tp_mtt.line_manager:
       class: %canal_tp_mtt.line_manager.class%
       arguments: ['@service_container', '@doctrine.orm.entity_manager', '@canal_tp_mtt.navitia']
    canal_tp_mtt.timetable_manager:
       class: %canal_tp_mtt.timetable_manager.class%
       arguments: ['@doctrine.orm.entity_manager', '@canal_tp_mtt.navitia', '@canal_tp_mtt.line_manager']
    canal_tp_mtt.block_manager:
       class: %canal_tp_mtt.block_manager.class%
       arguments: ['@doctrine.orm.entity_manager']
    canal_tp_mtt.stop_point_manager:
       class: %canal_tp_mtt.stop_point_manager.class%
       arguments: ['@service_container', '@doctrine.orm.entity_manager', '@canal_tp_mtt.navitia']
    canal_tp_mtt.form.factory.block:
       class: %canal_tp_mtt.form.factory.class%
       arguments: ['@service_container', '@doctrine.orm.entity_manager', '@form.factory', '@canaltp_media_manager_mtt']
    canal_tp_mtt.pdf_generator:
       class: %canal_tp_mtt.pdf_generator.class%
       arguments: ['%pdf_generator_url%', "%layouts%", "%kernel.root_dir%/../web/uploads/"]
    canal_tp_mtt.calendar_manager:
       class: %canal_tp_mtt.calendar_manager.class%
       arguments: ['@canal_tp_mtt.navitia', '@translator']
    canal_tp_mtt.season_manager:
       class: %canal_tp_mtt.season.class%
       arguments: ['@doctrine.orm.entity_manager']
    canal_tp_mtt.twig.schedule_extension:
        class: CanalTP\MttBundle\Twig\ScheduleExtension
        tags:
            - { name: twig.extension }
    canal_tp_mtt.twig.calendar_extension:
        class: CanalTP\MttBundle\Twig\CalendarExtension
        tags:
            - { name: twig.extension }
    canal_tp_mtt.frequency_manager:
       class: %canal_tp_mtt.frequency_manager.class%
       arguments: ['@doctrine.orm.entity_manager']
    canal_tp_mtt.network_manager:
       class: %canal_tp_mtt.network.class%
       arguments: ['@doctrine.orm.entity_manager']
