parameters:
    navitia_component.class: Navitia\Component\Service\ServiceFacade
    iussaad_navitia.class: CanalTP\IussaadBundle\Services\Navitia
    canal_tp_meth.navitia.class: CanalTP\MethBundle\Services\Navitia
    canal_tp_meth.line_manager.class: CanalTP\MethBundle\Services\LineManager
    canal_tp_meth.stop_point_manager.class: CanalTP\MethBundle\Services\StopPointManager
    canal_tp_meth.form.factory.class: CanalTP\MethBundle\Services\BlockTypeFactory
    canal_tp_meth.form.image_type_extension.class: CanalTP\MethBundle\Form\Extension\ImageTypeExtension

services:
    navitia_component:
        class:          "%navitia_component.class%"
        factory_class:  "%navitia_component.class%"
        factory_method: getInstance
        calls:
            - [ setConfiguration, [%config.navitia%]]

    iussaad_navitia:
        class: %iussaad_navitia.class%
        arguments: ['@navitia_component']
    canal_tp_meth.navitia:
       class: %canal_tp_meth.navitia.class%
       arguments: ['@navitia_component', '@iussaad_navitia']
    canal_tp_meth.line_manager:
       class: %canal_tp_meth.line_manager.class%
       arguments: ['@service_container', '@doctrine.orm.meth_entity_manager', '@canal_tp_meth.navitia']
    canal_tp_meth.stop_point_manager:
       class: %canal_tp_meth.stop_point_manager.class%
       arguments: ['@service_container', '@doctrine.orm.meth_entity_manager', '@canal_tp_meth.navitia']
    form.type.layout:
        class: CanalTP\MethBundle\Form\Type\LayoutType
        arguments:
            - "%layouts%"
        tags:
            - { name: form.type, alias: layout }
    canal_tp_meth.form.factory.block:
       class: %canal_tp_meth.form.factory.class%
       arguments: ['@service_container', '@doctrine.orm.meth_entity_manager', '@form.factory']
