parameters:
    canal_tp.media_manager.class: CanalTP\MediaManagerBundle\DataCollector\MediaDataCollector
    canal_tp_mtt.user.class: CanalTP\MttBundle\Services\UserManager
    canal_tp_mtt.navitia.class: CanalTP\MttBundle\Services\Navitia
    canal_tp_mtt.line_manager.class: CanalTP\MttBundle\Services\LineManager
    canal_tp_mtt.timetable_manager.class: CanalTP\MttBundle\Services\TimetableManager
    canal_tp_mtt.stop_point_manager.class: CanalTP\MttBundle\Services\StopPointManager
    canal_tp_mtt.calendar_manager.class: CanalTP\MttBundle\Services\CalendarManager
    canal_tp_mtt.form.factory.class: CanalTP\MttBundle\Services\BlockTypeFactory
    canal_tp_mtt.form.image_type_extension.class: CanalTP\MttBundle\Form\Extension\ImageTypeExtension
    canal_tp_mtt.pdf_generator.class: CanalTP\MttBundle\Services\PdfGenerator
    canal_tp_mtt.block_manager.class: CanalTP\MttBundle\Services\BlockManager
    canal_tp_mtt.frequency_manager.class: CanalTP\MttBundle\Services\FrequencyManager
    canal_tp_mtt.season.class: CanalTP\MttBundle\Services\SeasonManager
    canal_tp_mtt.network.class: CanalTP\MttBundle\Services\NetworkManager
    canal_tp.mtt.navitia_debug_matcher.class: CanalTP\MttBundle\Profiler\NavitiaDebugMatcher
    canal_tp.mtt.season_copier.class: CanalTP\MttBundle\Services\SeasonCopier
    canal_tp.mtt.media_manager.class: CanalTP\MttBundle\Services\MediaManager
    canal_tp.mtt.distribution_list.class: CanalTP\MttBundle\Services\DistributionListManager
    canal_tp.mtt.validator.constraints.navitia_network_id.class: CanalTP\MttBundle\Validator\Constraints\ConstainsNavitiaNetworkIdValidator

services:
    # constraint
    canal_tp.mtt.validator.constraints.navitia_network_id:
        class: %canal_tp.mtt.validator.constraints.navitia_network_id.class%
        arguments: ['@translator']
        tags:
            - { name: validator.constraint_validator, alias: validator_constraints_navitia_network_id }
    #TWIG extensions
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }
    canal_tp_mtt.twig.schedule_extension:
        class: CanalTP\MttBundle\Twig\ScheduleExtension
        tags:
            - { name: twig.extension }
    canal_tp_mtt.twig.calendar_extension:
        class: CanalTP\MttBundle\Twig\CalendarExtension
        tags:
            - { name: twig.extension }
    # Service of mediaManager
    canal_tp.media_manager:
        class: %canal_tp.media_manager.class%
        arguments: [%canal_tp_media_manager.configurations.mtt%]
    # MediaManagerMtt
    canal_tp_mtt.media_manager:
        class: %canal_tp.mtt.media_manager.class%
        arguments: ['@canal_tp.media_manager']
    # Copier
    canal_tp_mtt.season_copier:
        class: "%canal_tp.mtt.season_copier.class%"
        arguments: ['@doctrine.orm.entity_manager', '@canal_tp_mtt.line_manager', '@canal_tp_mtt.timetable_manager', '@canal_tp_mtt.stop_point_manager', '@canal_tp_mtt.block_manager', '@canal_tp_mtt.frequency_manager']
    #Profiler
    canal_tp_mtt.matcher.navitia_debug:
        class: "%canal_tp.mtt.navitia_debug_matcher.class%"
        arguments: ["@security.context"]
    # FORMS
    form.type.layout:
        class: CanalTP\MttBundle\Form\Type\LayoutType
        arguments:
            - "%layouts%"
        tags:
            - { name: form.type, alias: layout }
    form.type.datepicker:
        class: CanalTP\MttBundle\Form\Type\DatepickerType
        tags:
            - { name: form.type, alias: datepicker }
    canal_tp_mtt.user:
       class: %canal_tp_mtt.user.class%
       arguments: ['@doctrine.orm.entity_manager', '@translator']
    canal_tp_mtt.navitia:
       class: %canal_tp_mtt.navitia.class%
       arguments: ['@navitia_component', '@sam_navitia', '@translator']
    canal_tp_mtt.line_manager:
       class: %canal_tp_mtt.line_manager.class%
       arguments: ['@service_container', '@doctrine.orm.entity_manager', '@canal_tp_mtt.navitia']
    canal_tp_mtt.timetable_manager:
       class: %canal_tp_mtt.timetable_manager.class%
       arguments: ['@doctrine.orm.entity_manager', '@canal_tp_mtt.navitia', '@canal_tp_mtt.line_manager']
    canal_tp_mtt.block_manager:
       class: %canal_tp_mtt.block_manager.class%
       arguments: ['@doctrine.orm.entity_manager', '@canal_tp_mtt.media_manager']
    canal_tp_mtt.stop_point_manager:
       class: %canal_tp_mtt.stop_point_manager.class%
       arguments: ['@service_container', '@doctrine.orm.entity_manager', '@canal_tp_mtt.navitia']
    canal_tp_mtt.form.factory.block:
       class: %canal_tp_mtt.form.factory.class%
       arguments: ['@service_container', '@doctrine.orm.entity_manager', '@form.factory', '@canal_tp.media_manager']
    canal_tp_mtt.pdf_generator:
       class: %canal_tp_mtt.pdf_generator.class%
       arguments: ['%pdf_generator_url%', "%layouts%", "%kernel.root_dir%/../web/uploads/"]
    canal_tp_mtt.calendar_manager:
       class: %canal_tp_mtt.calendar_manager.class%
       arguments: ['@canal_tp_mtt.navitia', '@translator']
    canal_tp_mtt.season_manager:
       class: %canal_tp_mtt.season.class%
       arguments: ['@doctrine.orm.entity_manager']
    canal_tp_mtt.frequency_manager:
       class: %canal_tp_mtt.frequency_manager.class%
       arguments: ['@doctrine.orm.entity_manager']
    canal_tp_mtt.network_manager:
       class: %canal_tp_mtt.network.class%
       arguments: ['@doctrine.orm.entity_manager']
    # Service of distribution list
    canal_tp.mtt.distribution_list:
        class: %canal_tp.mtt.distribution_list.class%
        arguments: ['@doctrine.orm.entity_manager']
