parameters:
#    canal_tp_meth.example.class: CanalTP\MethBundle\Example

services:
#    canal_tp_meth.example:
#        class: %canal_tp_meth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
