CanalTP\MttBundle\Entity\Network:
    properties:
        externalCoverageId:
            - NotBlank: ~
        externalId:
            - CanalTP\MttBundle\Validator\Constraints\ConstainsNavitiaNetworkId: ~

CanalTP\MttBundle\Entity\Season:
    properties:
        title:
            - NotBlank: ~
            - Length:
                max: 255
        startDate:
            - DateTime: ~
        endDate:
            - DateTime: ~